import { Team } from "../app/store/league/league.model";

export const teams: Team[] = [
    {
      id: 1,
      name: 'Beşiktaş',
      points: 0,
      goalDifference: 0,
      matchesPlayed: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: 2,
      name: 'Fenerbahçe',
      points: 0,
      goalDifference: 0,
      matchesPlayed: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: 3,
      name: 'Galatasaray',
      points: 0,
      goalDifference: 0,
      matchesPlayed: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: 4,
      name: 'Trabzonspor',
      points: 0,
      goalDifference: 0,
      matchesPlayed: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: 5,
      name: 'Çaykur Rizespor',
      points: 0,
      goalDifference: 0,
      matchesPlayed: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: 6,
      name: 'Samsunspor',
      points: 0,
      goalDifference: 0,
      matchesPlayed: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: 7,
      name: 'Kayserispor',
      points: 0,
      goalDifference: 0,
      matchesPlayed: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: 8,
      name: 'Adana Demirspor',
      points: 0,
      goalDifference: 0,
      matchesPlayed: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
    {
      id: 9,
      name: 'Bursaspor',
      points: 0,
      goalDifference: 0,
      matchesPlayed: 0,
      wins: 0,
      losses: 0,
      draws: 0,
    },
  ];